### PR TITLE
Fix helm chart for filesystem with PVC cache

### PR DESCRIPTION
**Pull request by shaikatz**
I've tried to use the helm chart and found multiple issues.
I've tried to fix all of them.
I wonder how it even works for you guys? what am I doing wrong?

### CODE REVIEW

**Comment by jranson** [comment]
Hi @shaikatz thanks for this contribution. We are working hard on the helm chart under PR #370 (also see #352). We should have that merged in today and then we'll take a look at your PR here to see if it covered anything that we did not address.

**Comment by shaikatz** [comment]
Thanks @jranson looking forward to test the new version.

**Comment by jranson** [comment]
@shaikatz hey Shai, thanks for the PR. It looks like all the things addressed here were also included in #370, which we just merged to `master`. Would you mind doing a quick rebase and let us know if there's anything that you think still needs to be addressed? We appreciate the effort and are happy to bring in any additional improvements that you might have identified. Thanks again!

**Comment by shaikatz** [comment]
Thanks @jranson , I'll try the master version on Sunday and will close this PR if everything was fixed.

**Pull request closed without merging**
