### PR TITLE
Cleanup style

### PR DESCRIPTION
**Pull request by SuperQ**
* Add a `style` make target.
* Run tests in travis.
* `go fmt`.

### CODE REVIEW

**Comment by jranson** [comment]
Looks like we are getting test errors after these updates. I am re-running now to make sure it is not environmental.

**Comment by SuperQ** [comment]
From what I see in the test logs, it could be a flaky test.

**Comment by jranson** [comment]
I think there might be two separate issues. I can reproduce the filesystem cache test failure locally, but very intermittently (perhaps one out of every 30 runs). The tests are failing reliably on Travis, but only on the go:master tests. The two versioned go tests seem to work every time, except when they encounter the filesystem cache race condition. I'll take a look at the cache issue, but not sure what to make of the go:master issue.

**Comment by SuperQ** [comment]
I've removed the tests from Travis for now. Once the test issues are fixed, we can re-enable them in the test pipeline.

**Pull request merged**
