### PR TITLE
Properly set Content-Type

### PR DESCRIPTION
**Pull request by jacksontj**
Fixes the regression added in #196 

cc @jranson once this is merged, can we cut a release of the 0.x series?

### CODE REVIEW

**Comment by hatemosphere** [comment]
@jranson Any chances to port this fix for 1.x?

**Comment by jranson** [comment]
Hi @hatemosphere, this fix was actually in 1.x first; this PR is the back-port to 0.1.x

**Comment by hatemosphere** [comment]
@jranson so then i guess this https://github.com/Comcast/trickster/issues/216 is not related, right?

**Comment by jranson** [comment]
Correct, this issue here was around proxy-only requests and not assuming everything will be `application/json`, while the issue in #216 affects objects that are cached by Trickster and how upstream and downstream compression plays into automatic header creation for those objects at the time they are served. We will get 216 worked out today; sorry for the delay on that one!

**Pull request merged**
